import express from "express";
import createProduct from "../../controller/products/create-product.js";
import { limiter } from "../../utils/limiter.js";
import getProducts from "../../controller/products/get_products.js";
import { optionalAuth } from "../../middleware/optionalAuth.js";
import { isLoggedIn } from "../../middleware/isLoggedIn.js";
const router = express.Router();
router.post("/", limiter, isLoggedIn, createProduct);
router.get("/", optionalAuth, getProducts);
export { router };
