import { CartProvider } from "@/contexts/CartContext";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from 'react-hot-toast';
import "slick-carousel/slick/slick-theme.css";
import "slick-carousel/slick/slick.css";
import "./globals.css";
import SocketProvider from "@/providers/SocketProviders";
import { HuaweiBadge } from "@/components/HuaweiBadge";
import axios from "axios"

axios.defaults.headers.common["ngrok-skip-browser-warning"] = "true"
axios.defaults.withCredentials = true
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Deliva",
  description: "Generated by the Deliva team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
   
        <SocketProvider>
          <CartProvider>
            {children}
          </CartProvider>
        </SocketProvider>

        <Toaster />
      </body>
    </html>
  );
}
